const db = require('./db');

const parts = [
  // CURRENT PORTABLE RADIOS - MOTOTRBO R7 SERIES (2024-2025)
  {
    sku: 'R7-VHF-136-174',
    name: 'MOTOTRBO R7 Portable Radio - VHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO R7 Series',
    brand: 'Motorola',
    model: 'R7',
    description: 'Advanced portable with slim high-capacity battery, VHF 136-174 MHz, advanced audio processing, Bluetooth',
    cost: 420.00,
    price: 695.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 35,
    reorder_level: 8
  },
  {
    sku: 'R7-UHF-403-470',
    name: 'MOTOTRBO R7 Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO R7 Series',
    brand: 'Motorola',
    model: 'R7',
    description: 'Advanced portable with slim high-capacity battery, UHF 403-470 MHz, advanced audio processing, Bluetooth',
    cost: 425.00,
    price: 705.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 42,
    reorder_level: 10
  },

  // CURRENT XPR 3000e SERIES (2024-2025)
  {
    sku: 'XPR3300e-VHF',
    name: 'XPR 3300e Portable Radio - VHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO XPR3000e',
    brand: 'Motorola',
    model: 'XPR3300e',
    description: 'Next-generation digital radio, 28-hour battery life, noise cancellation, VHF 136-174 MHz, Wi-Fi updates',
    cost: 295.00,
    price: 485.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 58,
    reorder_level: 12
  },
  {
    sku: 'XPR3300e-UHF',
    name: 'XPR 3300e Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO XPR3000e',
    brand: 'Motorola',
    model: 'XPR3300e',
    description: 'Next-generation digital radio, 28-hour battery life, noise cancellation, UHF 403-470 MHz, Wi-Fi updates',
    cost: 300.00,
    price: 495.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 48,
    reorder_level: 10
  },
  {
    sku: 'XPR3500e-UHF',
    name: 'XPR 3500e Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO XPR3000e',
    brand: 'Motorola',
    model: 'XPR3500e',
    description: 'Next-generation with monochrome display, limited keypad, 28-hour battery, UHF 403-470 MHz, Wi-Fi',
    cost: 335.00,
    price: 555.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 36,
    reorder_level: 8
  },
  {
    sku: 'XPR3500e-VHF',
    name: 'XPR 3500e Portable Radio - VHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO XPR3000e',
    brand: 'Motorola',
    model: 'XPR3500e',
    description: 'Next-generation with monochrome display, limited keypad, 28-hour battery, VHF 136-174 MHz, Wi-Fi',
    cost: 330.00,
    price: 545.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 32,
    reorder_level: 8
  },

  // MOTOTRBO R2 SERIES (Budget Commercial)
  {
    sku: 'R2-UHF-403-470',
    name: 'MOTOTRBO R2 Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO R2 Series',
    brand: 'Motorola',
    model: 'R2',
    description: 'Entry-level digital radio, UHF 403-470 MHz, 16 channels, rugged design',
    cost: 185.00,
    price: 310.00,
    labor_hours: 0.25,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 65,
    reorder_level: 15
  },
  {
    sku: 'CP100d-UHF',
    name: 'CP100d Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO R2 Series',
    brand: 'Motorola',
    model: 'CP100d',
    description: 'Digital entry-level radio with 1750mAh battery, UHF 403-470 MHz, simple operation',
    cost: 165.00,
    price: 275.00,
    labor_hours: 0.25,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital',
    inventory_qty: 78,
    reorder_level: 18
  },

  // SL SERIES ULTRA-SLIM
  {
    sku: 'SL3500e-UHF',
    name: 'SL3500e Ultra-Slim Portable - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO SL Series',
    brand: 'Motorola',
    model: 'SL3500e',
    description: 'Ultra-slim design, 2300mAh Li-ion battery, micro-USB charging, UHF 403-470 MHz',
    cost: 380.00,
    price: 625.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 28,
    reorder_level: 6
  },
  {
    sku: 'SL3500e-VHF',
    name: 'SL3500e Ultra-Slim Portable - VHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO SL Series',
    brand: 'Motorola',
    model: 'SL3500e',
    description: 'Ultra-slim design, 2300mAh Li-ion battery, micro-USB charging, VHF 136-174 MHz',
    cost: 375.00,
    price: 615.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 24,
    reorder_level: 5
  },
  {
    sku: 'XPR7550e-UHF',
    name: 'XPR 7550e Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO Digital',
    brand: 'Motorola',
    model: 'XPR7550e',
    description: 'Premium portable with full-color display, GPS, Bluetooth, UHF 403-470 MHz, 4W, IP68 rated',
    cost: 520.00,
    price: 875.00,
    labor_hours: 0.75,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 28,
    reorder_level: 5
  },
  {
    sku: 'XPR7580e-IS-UHF',
    name: 'XPR 7580e IS Portable Radio - UHF',
    category: 'Portable Radios',
    subcategory: 'MOTOTRBO Digital IS',
    brand: 'Motorola',
    model: 'XPR7580e-IS',
    description: 'Intrinsically Safe portable for hazardous environments, UHF 403-470 MHz, 4W, TIA-4950 certified',
    cost: 680.00,
    price: 1150.00,
    labor_hours: 0.75,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 12,
    reorder_level: 3
  },

  // CURRENT MOBILE RADIOS - XPR 5000e SERIES (2024-2025)
  {
    sku: 'XPR5350e-VHF-25W',
    name: 'XPR 5350e Mobile Radio - VHF 25W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5350e',
    description: 'Advanced mobile with voice/data, Wi-Fi updates, location tracking, VHF 136-174 MHz, 25W',
    cost: 685.00,
    price: 1145.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 18,
    reorder_level: 4
  },
  {
    sku: 'XPR5350e-VHF-45W',
    name: 'XPR 5350e Mobile Radio - VHF 45W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5350e',
    description: 'Advanced mobile with voice/data, Wi-Fi updates, location tracking, VHF 136-174 MHz, 45W',
    cost: 735.00,
    price: 1225.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 15,
    reorder_level: 3
  },
  {
    sku: 'XPR5350e-UHF-25W',
    name: 'XPR 5350e Mobile Radio - UHF 25W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5350e',
    description: 'Advanced mobile with voice/data, Wi-Fi updates, location tracking, UHF 403-470 MHz, 25W',
    cost: 695.00,
    price: 1155.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 22,
    reorder_level: 5
  },
  {
    sku: 'XPR5350e-UHF-40W',
    name: 'XPR 5350e Mobile Radio - UHF 40W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5350e',
    description: 'Advanced mobile with voice/data, Wi-Fi updates, location tracking, UHF 403-470 MHz, 40W',
    cost: 745.00,
    price: 1235.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 16,
    reorder_level: 4
  },
  {
    sku: 'XPR5550e-UHF-45W',
    name: 'XPR 5550e Mobile Radio - UHF 45W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5550e',
    description: 'Premium mobile with color display, GPS, Bluetooth, indoor/outdoor location tracking, UHF 403-470 MHz, 45W',
    cost: 825.00,
    price: 1375.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 12,
    reorder_level: 3
  },
  {
    sku: 'XPR5550e-VHF-45W',
    name: 'XPR 5550e Mobile Radio - VHF 45W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR5000e',
    brand: 'Motorola',
    model: 'XPR5550e',
    description: 'Premium mobile with color display, GPS, Bluetooth, indoor/outdoor location tracking, VHF 136-174 MHz, 45W',
    cost: 815.00,
    price: 1355.00,
    labor_hours: 2.5,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 10,
    reorder_level: 2
  },

  // CURRENT XPR 2500 SERIES (Budget Mobile)
  {
    sku: 'XPR2500-VHF-25W',
    name: 'XPR 2500 Mobile Radio - VHF 25W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR2500',
    brand: 'Motorola',
    model: 'XPR2500',
    description: 'Compact mobile radio, automatic volume adjustment, VHF 136-174 MHz, 25W',
    cost: 545.00,
    price: 908.00,
    labor_hours: 2.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 28,
    reorder_level: 6
  },
  {
    sku: 'XPR2500-UHF-25W',
    name: 'XPR 2500 Mobile Radio - UHF 25W',
    category: 'Mobile Radios',
    subcategory: 'MOTOTRBO XPR2500',
    brand: 'Motorola',
    model: 'XPR2500',
    description: 'Compact mobile radio, automatic volume adjustment, UHF 403-470 MHz, 25W',
    cost: 555.00,
    price: 925.00,
    labor_hours: 2.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 32,
    reorder_level: 8
  },

  // CURRENT REPEATERS - SLR SERIES (2024-2025)
  {
    sku: 'SLR8000-UHF-100W',
    name: 'SLR 8000 Repeater - UHF 100W',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR8000',
    description: 'High-performance 100W repeater, 2U rack mount, supports all MOTOTRBO architectures, UHF 403-470 MHz',
    cost: 3850.00,
    price: 6425.00,
    labor_hours: 10.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 2,
    reorder_level: 1
  },
  {
    sku: 'SLR8000-VHF-100W',
    name: 'SLR 8000 Repeater - VHF 100W',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR8000',
    description: 'High-performance 100W repeater, 2U rack mount, supports all MOTOTRBO architectures, VHF 136-174 MHz',
    cost: 3850.00,
    price: 6425.00,
    labor_hours: 10.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 1,
    reorder_level: 1
  },
  {
    sku: 'SLR5700-UHF',
    name: 'SLR 5700 Repeater - UHF',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR5700',
    description: '50W "slim" commercial repeater, 1U rack mount, 64 channels, dual ethernet, UHF 403-470 MHz',
    cost: 2950.00,
    price: 4915.00,
    labor_hours: 8.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 4,
    reorder_level: 1
  },
  {
    sku: 'SLR5700-VHF',
    name: 'SLR 5700 Repeater - VHF',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR5700',
    description: '50W "slim" commercial repeater, 1U rack mount, 64 channels, dual ethernet, VHF 136-174 MHz',
    cost: 2950.00,
    price: 4915.00,
    labor_hours: 8.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 3,
    reorder_level: 1
  },
  {
    sku: 'SLR1000-UHF',
    name: 'SLR 1000 Repeater - UHF',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR1000',
    description: 'Compact outdoor repeater, IP65 rated, supports conventional and trunking, UHF 403-470 MHz',
    cost: 1850.00,
    price: 3085.00,
    labor_hours: 6.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'UHF',
    system_type: 'Digital/Analog',
    inventory_qty: 6,
    reorder_level: 2
  },
  {
    sku: 'SLR1000-VHF',
    name: 'SLR 1000 Repeater - VHF',
    category: 'Repeaters',
    subcategory: 'MOTOTRBO SLR Series',
    brand: 'Motorola',
    model: 'SLR1000',
    description: 'Compact outdoor repeater, IP65 rated, supports conventional and trunking, VHF 136-174 MHz',
    cost: 1850.00,
    price: 3085.00,
    labor_hours: 6.0,
    compatibility: 'MOTOTRBO',
    requires_licensing: 1,
    frequency_band: 'VHF',
    system_type: 'Digital/Analog',
    inventory_qty: 4,
    reorder_level: 1
  },

  // CURRENT BATTERIES (2024-2025)
  {
    sku: 'PMNN4598',
    name: 'PMNN4598 Standard Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4598',
    description: 'Standard Li-ion battery for MOTOTRBO R2 series radios, 1750 mAh',
    cost: 24.00,
    price: 39.95,
    labor_hours: 0.0,
    compatibility: 'MOTOTRBO R2 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 185,
    reorder_level: 35
  },
  {
    sku: 'PMNN4476A',
    name: 'PMNN4476A Li-ion Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4476A',
    description: '1750mAh Li-ion battery for CP100d and XPR 3000e series radios',
    cost: 32.00,
    price: 53.00,
    labor_hours: 0.0,
    compatibility: 'CP100d, XPR3000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 165,
    reorder_level: 30
  },
  {
    sku: 'PMNN4468',
    name: 'PMNN4468 Slim Li-ion Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4468',
    description: '1600mAh slim Li-ion battery for XPR 3000e series, 28-hour operation',
    cost: 28.00,
    price: 46.95,
    labor_hours: 0.0,
    compatibility: 'XPR3000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 145,
    reorder_level: 25
  },
  {
    sku: 'PMNN4544A',
    name: 'PMNN4544A Low Voltage Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4544A',
    description: '3000mAh low voltage Li-ion battery for XPR 3000e series, extended life',
    cost: 48.00,
    price: 79.95,
    labor_hours: 0.0,
    compatibility: 'XPR3000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 98,
    reorder_level: 18
  },
  {
    sku: 'PMNN4807',
    name: 'PMNN4807 High Capacity Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4807',
    description: 'High-capacity slim battery with new lithium cells for MOTOTRBO R7',
    cost: 52.00,
    price: 86.95,
    labor_hours: 0.0,
    compatibility: 'MOTOTRBO R7 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 78,
    reorder_level: 15
  },
  {
    sku: 'PMNN4095',
    name: 'PMNN4095 SL Series Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4095',
    description: '2300mAh Li-ion battery for SL3500e ultra-slim radios',
    cost: 45.00,
    price: 74.95,
    labor_hours: 0.0,
    compatibility: 'SL3500e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 64,
    reorder_level: 12
  },
  {
    sku: 'PMNN4491',
    name: 'PMNN4491 IMPRES Li-ion Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4491',
    description: 'IMPRES Li-ion battery pack for XPR 7000e series, 2300 mAh, smart charging',
    cost: 56.50,
    price: 93.95,
    labor_hours: 0.0,
    compatibility: 'XPR7000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 94,
    reorder_level: 15
  },
  {
    sku: 'PMNN4493',
    name: 'PMNN4493 IMPRES Low Voltage Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4493',
    description: 'IMPRES Low Voltage Li-ion battery for XPR 7000e series',
    cost: 67.00,
    price: 110.95,
    labor_hours: 0.0,
    compatibility: 'XPR7000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 78,
    reorder_level: 12
  },
  {
    sku: 'PMNN4600',
    name: 'PMNN4600 Slim Li-ion Battery',
    category: 'Accessories',
    subcategory: 'Batteries',
    brand: 'Motorola',
    model: 'PMNN4600',
    description: 'Slim Li-ion battery pack, 2100 mAh, for XPR 7000e series',
    cost: 74.00,
    price: 123.00,
    labor_hours: 0.0,
    compatibility: 'XPR7000e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 62,
    reorder_level: 10
  },

  // CURRENT CHARGERS (2024-2025)
  {
    sku: 'PMPN4173A',
    name: 'PMPN4173A Desktop Charger',
    category: 'Accessories',
    subcategory: 'Chargers',
    brand: 'Motorola',
    model: 'PMPN4173A',
    description: 'Single unit desktop charger with power supply for MOTOTRBO R2, CP100d',
    cost: 38.50,
    price: 64.00,
    labor_hours: 0.0,
    compatibility: 'MOTOTRBO R2, CP100d',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 85,
    reorder_level: 18
  },
  {
    sku: 'PMLN7190',
    name: 'PMLN7190 Micro-USB Charger',
    category: 'Accessories',
    subcategory: 'Chargers',
    brand: 'Motorola',
    model: 'PMLN7190',
    description: 'Standard micro-USB charger for SL3500e ultra-slim radios',
    cost: 22.00,
    price: 36.00,
    labor_hours: 0.0,
    compatibility: 'SL3500e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 45,
    reorder_level: 10
  },
  {
    sku: 'PMPN4137A',
    name: 'PMPN4137A IMPRES Charger',
    category: 'Accessories',
    subcategory: 'Chargers',
    brand: 'Motorola',
    model: 'PMPN4137A',
    description: 'IMPRES single-unit desktop charger for XPR 3000e and R7 series',
    cost: 52.00,
    price: 86.00,
    labor_hours: 0.0,
    compatibility: 'XPR3000e, R7 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 58,
    reorder_level: 12
  },
  {
    sku: 'PMLN6598A',
    name: 'PMLN6598A Multi-Unit Charger',
    category: 'Accessories',
    subcategory: 'Chargers',
    brand: 'Motorola',
    model: 'PMLN6598A',
    description: '6-bay multi-unit IMPRES charger for current MOTOTRBO series',
    cost: 315.00,
    price: 525.00,
    labor_hours: 0.5,
    compatibility: 'MOTOTRBO R2, R7, XPR series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 18,
    reorder_level: 4
  },
  {
    sku: 'PMLN6589A',
    name: 'PMLN6589A 12-Slot Charger',
    category: 'Accessories',
    subcategory: 'Chargers',
    brand: 'Motorola',
    model: 'PMLN6589A',
    description: '12-slot multi-unit charger for high-volume operations',
    cost: 485.00,
    price: 808.00,
    labor_hours: 1.0,
    compatibility: 'MOTOTRBO R2, R7, XPR series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 8,
    reorder_level: 2
  },

  // CURRENT ANTENNAS (2024-2025)
  {
    sku: 'PMAE4095',
    name: 'PMAE4095 UHF Antenna',
    category: 'Accessories',
    subcategory: 'Antennas',
    brand: 'Motorola',
    model: 'PMAE4095',
    description: 'Standard UHF antenna for SL3500e ultra-slim radios, 403-470 MHz',
    cost: 6.50,
    price: 10.75,
    labor_hours: 0.0,
    compatibility: 'SL3500e UHF',
    requires_licensing: 0,
    frequency_band: 'UHF',
    system_type: null,
    inventory_qty: 125,
    reorder_level: 25
  },
  {
    sku: 'PMAD4145',
    name: 'PMAD4145 VHF Antenna',
    category: 'Accessories',
    subcategory: 'Antennas',
    brand: 'Motorola',
    model: 'PMAD4145',
    description: 'Standard VHF antenna for SL3500e ultra-slim radios, 136-174 MHz',
    cost: 6.25,
    price: 10.50,
    labor_hours: 0.0,
    compatibility: 'SL3500e VHF',
    requires_licensing: 0,
    frequency_band: 'VHF',
    system_type: null,
    inventory_qty: 115,
    reorder_level: 22
  },
  {
    sku: 'PMAE4003A',
    name: 'PMAE4003A UHF Stubby Antenna',
    category: 'Accessories',
    subcategory: 'Antennas',
    brand: 'Motorola',
    model: 'PMAE4003A',
    description: 'Enhanced UHF stubby antenna for R7 and XPR portables, 403-470 MHz',
    cost: 7.80,
    price: 13.00,
    labor_hours: 0.0,
    compatibility: 'R7, XPR series UHF',
    requires_licensing: 0,
    frequency_band: 'UHF',
    system_type: null,
    inventory_qty: 185,
    reorder_level: 35
  },
  {
    sku: 'PMAD4170',
    name: 'PMAD4170 VHF/GPS Antenna',
    category: 'Accessories',
    subcategory: 'Antennas',
    brand: 'Motorola',
    model: 'PMAD4170',
    description: 'Advanced VHF/GPS combination antenna for R7 series, enhanced performance',
    cost: 9.50,
    price: 15.75,
    labor_hours: 0.0,
    compatibility: 'R7 VHF with GPS',
    requires_licensing: 0,
    frequency_band: 'VHF',
    system_type: null,
    inventory_qty: 95,
    reorder_level: 18
  },
  {
    sku: 'PMAE4016',
    name: 'PMAE4016 High-Gain UHF Antenna',
    category: 'Accessories',
    subcategory: 'Antennas',
    brand: 'Motorola',
    model: 'PMAE4016',
    description: 'High-gain UHF antenna for extended range, R2 and XPR series',
    cost: 8.95,
    price: 14.95,
    labor_hours: 0.0,
    compatibility: 'R2, XPR series UHF',
    requires_licensing: 0,
    frequency_band: 'UHF',
    system_type: null,
    inventory_qty: 145,
    reorder_level: 28
  },

  // AUDIO ACCESSORIES
  {
    sku: 'VOXTRONIX-P8500M-R',
    name: 'Voxtronix P8500M-R Swivel Headset',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Voxtronix',
    model: 'P8500M-R',
    description: 'Swivel boom headset for Motorola radios with inline PTT',
    cost: 13.20,
    price: 22.00,
    labor_hours: 0.0,
    compatibility: 'Motorola radios',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 86,
    reorder_level: 20
  },
  {
    sku: 'PMMN4029',
    name: 'PMMN4029 Speaker Microphone',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Motorola',
    model: 'PMMN4029',
    description: 'IP57 waterproof remote speaker microphone with 3.5mm audio jack',
    cost: 48.75,
    price: 81.00,
    labor_hours: 0.0,
    compatibility: 'XPR series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 73,
    reorder_level: 15
  },
  {
    sku: 'PMMN4073',
    name: 'PMMN4073 IMPRES RSM',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Motorola',
    model: 'PMMN4073',
    description: 'IMPRES remote speaker microphone, small, UL approved',
    cost: 54.00,
    price: 90.00,
    labor_hours: 0.0,
    compatibility: 'IMPRES compatible radios',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 58,
    reorder_level: 12
  },
  {
    sku: 'PMMN4125',
    name: 'PMMN4125 Remote Speaker Microphone',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Motorola',
    model: 'PMMN4125',
    description: 'Rugged remote speaker microphone with emergency button and LED',
    cost: 71.00,
    price: 118.00,
    labor_hours: 0.0,
    compatibility: 'XPR series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 46,
    reorder_level: 10
  },
  {
    sku: 'RLN6562',
    name: 'RLN6562 Bluetooth RSM',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Motorola',
    model: 'RLN6562',
    description: 'Operations Critical Bluetooth Remote Speaker Microphone',
    cost: 154.50,
    price: 257.00,
    labor_hours: 0.25,
    compatibility: 'Bluetooth enabled XPR',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 21,
    reorder_level: 5
  },
  {
    sku: 'RLN6554A',
    name: 'RLN6554A Wireless RSM',
    category: 'Accessories',
    subcategory: 'Audio',
    brand: 'Motorola',
    model: 'RLN6554A',
    description: 'Wireless Remote Speaker Microphone with advanced features',
    cost: 321.60,
    price: 534.00,
    labor_hours: 0.25,
    compatibility: 'Advanced XPR series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 8,
    reorder_level: 2
  },

  // CURRENT CARRYING ACCESSORIES (2024-2025)
  {
    sku: 'PMLN7008',
    name: 'PMLN7008 Standard Belt Clip',
    category: 'Accessories',
    subcategory: 'Carrying',
    brand: 'Motorola',
    model: 'PMLN7008',
    description: 'Standard belt clip for MOTOTRBO R2 series',
    cost: 6.95,
    price: 11.50,
    labor_hours: 0.0,
    compatibility: 'MOTOTRBO R2 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 285,
    reorder_level: 55
  },
  {
    sku: 'PMLN7190A',
    name: 'PMLN7190A Standard Belt Clip',
    category: 'Accessories',
    subcategory: 'Carrying',
    brand: 'Motorola',
    model: 'PMLN7190A',
    description: 'Standard belt clip for SL3500e ultra-slim radios',
    cost: 7.50,
    price: 12.50,
    labor_hours: 0.0,
    compatibility: 'SL3500e series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 165,
    reorder_level: 32
  },
  {
    sku: 'PMLN7238',
    name: 'PMLN7238 Belt Clip',
    category: 'Accessories',
    subcategory: 'Carrying',
    brand: 'Motorola',
    model: 'PMLN7238',
    description: 'Enhanced belt clip for XPR 3000e and R7 series',
    cost: 8.95,
    price: 14.95,
    labor_hours: 0.0,
    compatibility: 'XPR3000e, R7 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 195,
    reorder_level: 38
  },
  {
    sku: 'PMLN5870',
    name: 'PMLN5870 Leather Case',
    category: 'Accessories',
    subcategory: 'Carrying',
    brand: 'Motorola',
    model: 'PMLN5870',
    description: 'Premium leather carrying case with belt clip for portable radios',
    cost: 24.50,
    price: 40.75,
    labor_hours: 0.0,
    compatibility: 'R2, XPR3000e, R7 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 78,
    reorder_level: 15
  },
  {
    sku: 'PMLN5868',
    name: 'PMLN5868 Nylon Case',
    category: 'Accessories',
    subcategory: 'Carrying',
    brand: 'Motorola',
    model: 'PMLN5868',
    description: 'Durable nylon carrying case with D-ring for harsh environments',
    cost: 18.95,
    price: 31.50,
    labor_hours: 0.0,
    compatibility: 'R2, XPR3000e, R7 series',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 125,
    reorder_level: 24
  },
  {
    sku: 'VEH-INSTALL',
    name: 'Vehicle Mobile Installation Kit',
    category: 'Installation',
    subcategory: 'Vehicle',
    brand: 'Generic',
    model: 'VEH-KIT',
    description: 'Complete vehicle installation kit including antenna, mount, cable, and hardware',
    cost: 120.00,
    price: 200.00,
    labor_hours: 3.0,
    compatibility: 'Mobile radios',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 32,
    reorder_level: 8
  },
  {
    sku: 'ANT-BASE-UHF',
    name: 'UHF Base Station Antenna',
    category: 'Installation',
    subcategory: 'Base Station',
    brand: 'Generic',
    model: 'BASE-UHF',
    description: 'High-gain UHF base station antenna, 403-470 MHz, 6 dBd gain',
    cost: 180.00,
    price: 300.00,
    labor_hours: 4.0,
    compatibility: 'UHF repeaters/base stations',
    requires_licensing: 0,
    frequency_band: 'UHF',
    system_type: null,
    inventory_qty: 12,
    reorder_level: 3
  },
  {
    sku: 'ANT-BASE-VHF',
    name: 'VHF Base Station Antenna',
    category: 'Installation',
    subcategory: 'Base Station',
    brand: 'Generic',
    model: 'BASE-VHF',
    description: 'High-gain VHF base station antenna, 136-174 MHz, 6 dBd gain',
    cost: 175.00,
    price: 290.00,
    labor_hours: 4.0,
    compatibility: 'VHF repeaters/base stations',
    requires_licensing: 0,
    frequency_band: 'VHF',
    system_type: null,
    inventory_qty: 8,
    reorder_level: 2
  },

  // LICENSING AND SERVICES
  {
    sku: 'FCC-LICENSE',
    name: 'FCC License Application',
    category: 'Services',
    subcategory: 'Licensing',
    brand: 'FCC',
    model: 'LICENSE',
    description: 'FCC license application and coordination service (10-year license)',
    cost: 400.00,
    price: 800.00,
    labor_hours: 4.0,
    compatibility: 'All systems',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 999,
    reorder_level: 1
  },
  {
    sku: 'PROGRAMMING-SERVICE',
    name: 'Radio Programming Service',
    category: 'Services',
    subcategory: 'Programming',
    brand: 'Service',
    model: 'PROG',
    description: 'Professional radio programming service per radio',
    cost: 25.00,
    price: 50.00,
    labor_hours: 0.5,
    compatibility: 'All Motorola radios',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 999,
    reorder_level: 1
  },
  {
    sku: 'SITE-SURVEY',
    name: 'Site Survey and Coverage Analysis',
    category: 'Services',
    subcategory: 'Engineering',
    brand: 'Service',
    model: 'SURVEY',
    description: 'Professional site survey and RF coverage analysis',
    cost: 300.00,
    price: 600.00,
    labor_hours: 8.0,
    compatibility: 'All systems',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 999,
    reorder_level: 1
  },
  {
    sku: 'SYSTEM-DESIGN',
    name: 'System Design and Engineering',
    category: 'Services',
    subcategory: 'Engineering',
    brand: 'Service',
    model: 'DESIGN',
    description: 'Complete system design and engineering services',
    cost: 500.00,
    price: 1000.00,
    labor_hours: 16.0,
    compatibility: 'All systems',
    requires_licensing: 0,
    frequency_band: null,
    system_type: null,
    inventory_qty: 999,
    reorder_level: 1
  }
];

const clients = [
  {
    name: 'Lincoln Elementary School',
    industry: 'Education',
    contact_person: 'Sarah Johnson',
    email: 'sarah.johnson@lincoln.edu',
    phone: '555-123-4567',
    address: '123 School Lane, Anytown, ST 12345',
    current_system: 'Analog FRS radios',
    coverage_area: 'Single building, 3 floors, gymnasium',
    user_count: 25,
    locations: 'Main building, portable classrooms',
    special_requirements: 'Emergency lockdown capability, quiet operation',
    discount_level: 0.10
  },
  {
    name: 'Metro Warehouse Solutions',
    industry: 'Warehousing',
    contact_person: 'Mike Rodriguez',
    email: 'mike.r@metrowarehouse.com',
    phone: '555-987-6543',
    address: '4567 Industrial Blvd, Commerce City, ST 67890',
    current_system: 'Old Kenwood analog system',
    coverage_area: '350,000 sq ft warehouse, 30ft high racks',
    user_count: 45,
    locations: 'Main warehouse, loading docks, offices',
    special_requirements: 'Forklift mounting, noise cancellation',
    discount_level: 0.15
  },
  {
    name: 'Sunrise Construction Company',
    industry: 'Construction',
    contact_person: 'David Chen',
    email: 'david@sunriseconstruction.com',
    phone: '555-456-7890',
    address: '789 Builder St, Construction City, ST 11111',
    current_system: 'Consumer-grade walkie talkies',
    coverage_area: 'Multi-site, up to 5 mile radius',
    user_count: 35,
    locations: 'Multiple job sites, office trailer',
    special_requirements: 'Rugged for harsh environments, long battery life',
    discount_level: 0.20
  },
  {
    name: 'Regional Medical Center',
    industry: 'Healthcare',
    contact_person: 'Dr. Lisa Thompson',
    email: 'lthompson@regionalmed.org',
    phone: '555-234-5678',
    address: '1000 Health Plaza, Medical City, ST 22222',
    current_system: 'Overhead paging only',
    coverage_area: '5-building campus, underground tunnels',
    user_count: 120,
    locations: 'Main hospital, outbuildings, parking structures',
    special_requirements: 'Hospital-grade, emergency coordination',
    discount_level: 0.12
  },
  {
    name: 'Mountain View Manufacturing',
    industry: 'Manufacturing',
    contact_person: 'Jennifer Martinez',
    email: 'jmartinez@mvmanufacturing.com',
    phone: '555-876-5432',
    address: '2500 Factory Drive, Industrial Park, ST 33333',
    current_system: 'Older Motorola analog system',
    coverage_area: '280,000 sq ft production floor, 3 shifts',
    user_count: 65,
    locations: 'Main factory, shipping dock, quality lab',
    special_requirements: 'Noise cancellation, 24/7 operation',
    discount_level: 0.18
  }
];

function seedDatabase() {
  console.log('🌱 Starting database seeding...');

  // Clear existing data
  db.run('DELETE FROM parts');
  db.run('DELETE FROM clients');

  // Insert parts
  const insertPart = db.prepare(`
    INSERT INTO parts (sku, name, category, subcategory, brand, model, description,
                      cost, price, labor_hours, compatibility, requires_licensing,
                      frequency_band, system_type, inventory_qty, reorder_level)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  parts.forEach(part => {
    insertPart.run(
      part.sku, part.name, part.category, part.subcategory, part.brand, part.model,
      part.description, part.cost, part.price, part.labor_hours, part.compatibility,
      part.requires_licensing, part.frequency_band, part.system_type,
      part.inventory_qty || 0, part.reorder_level || 0
    );
  });

  insertPart.finalize();

  // Insert clients
  const insertClient = db.prepare(`
    INSERT INTO clients (name, industry, contact_person, email, phone, address,
                        current_system, coverage_area, user_count, locations,
                        special_requirements, discount_level)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  clients.forEach(client => {
    insertClient.run(
      client.name, client.industry, client.contact_person, client.email, client.phone,
      client.address, client.current_system, client.coverage_area, client.user_count,
      client.locations, client.special_requirements, client.discount_level
    );
  });

  insertClient.finalize();

  console.log(`✅ Seeded database with ${parts.length} parts and ${clients.length} clients`);
  console.log(`📦 Inventory levels loaded for realistic stock management`);
}

module.exports = { seedDatabase };